---
- name: Create Prometheus Directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: steven
    group: steven
  with_items:
    - /home/steven/node_exporter/
  become: yes

- name: extract node_exporter zip
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ exporter_version }}/node_exporter-{{ exporter_version }}.linux-amd64.tar.gz
    #src: https://github.com/prometheus/node_exporter/releases/download/v1.0.0-rc.0/node_exporter-1.0.0-rc.0.linux-amd64.tar.gz
    dest: /home/steven/node_exporter/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: move to path
  copy:
    src: /home/steven/node_exporter/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    group: steven
    owner: steven
    mode: 0755
  become: yes

- name: create systemd unit file
  template:
    src: ./templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  become: yes

- name: disable firewalld systemd
  shell: $(systemctl disable firewalld && systemctl stop firewalld) || true
  become: yes

- name: enable node_exporter systemd 
  systemd:
    name: node_exporter
    state: started
    # This is bugged?
    daemon_reload: yes
    enabled: yes
  become: yes

